CREATE TABLE GENRES 
(
  CODE CHAR(5) NOT NULL 
, LIBELLE VARCHAR2(80) NOT NULL 
, CONSTRAINT GENRES_PK PRIMARY KEY 
  (
    CODE 
  )
  ENABLE 
);

INSERT INTO GENRES (CODE, LIBELLE) VALUES ('REC', 'Récit')
INSERT INTO GENRES (CODE, LIBELLE) VALUES ('POL', 'Policier')
INSERT INTO GENRES (CODE, LIBELLE) VALUES ('BD', 'Bande Dessinée')
INSERT INTO GENRES (CODE, LIBELLE) VALUES ('INF', 'Informatique')
INSERT INTO GENRES (CODE, LIBELLE) VALUES ('THE', 'Théâtre')
INSERT INTO GENRES (CODE, LIBELLE) VALUES ('ROM', 'Roman')