CREATE TABLE GENRES 
(
  CODE CHAR(5) NOT NULL 
, LIBELLE VARCHAR2(80) NOT NULL 
, CONSTRAINT GENRES_PK PRIMARY KEY 
  (
    CODE 
  )
  ENABLE 
);

INSERT INTO "C##ROOT"."GENRES" (CODE, LIBELLE) VALUES ('REC', 'Récit')
INSERT INTO "C##ROOT"."GENRES" (CODE, LIBELLE) VALUES ('POL', 'Policier')
INSERT INTO "C##ROOT"."GENRES" (CODE, LIBELLE) VALUES ('BD', 'Bande Dessinée')
INSERT INTO "C##ROOT"."GENRES" (CODE, LIBELLE) VALUES ('INF', 'Informatique')
INSERT INTO "C##ROOT"."GENRES" (CODE, LIBELLE) VALUES ('THE', 'Théâtre')
INSERT INTO "C##ROOT"."GENRES" (CODE, LIBELLE) VALUES ('ROM', 'Roman')