create or replace TRIGGER TRIGG_AUTOINCREMENT_MEMBRES 
BEFORE INSERT ON MEMBRES FOR EACH ROW
BEGIN
  SELECT SEQ_MEMBRES.nextval INTO :new.numero FROM DUAL;
  EXCEPTION
    WHEN OTHERS THEN
        NULL;
END;